// Preliminary code generated by ChatGPT

const io = require("socket.io-client");
const axios = require("axios");
const fs = require("fs");
const fastq = require("fastq");

// Parse the command line arguments to get the config file path
const [, , configFilePath] = process.argv;

// Read the config file
const config = JSON.parse(fs.readFileSync(configFilePath));

// Connect to the server using socket.io
const socket = io(config.server_url, {
    query: {
        // Add the authentication token as a query parameter
        token: config.auth_token
    }
});

// Create a fastq worker to handle incoming JSON strings
const worker = fastq(async (jsonStr, cb) => {
    // Parse the JSON string into an object
    const reqObj = JSON.parse(jsonStr);

    // Log the URL of the incoming request
    console.log(`Received request for URL: ${reqObj.url}`);

    // Make an HTTP request to the endpoint defined in the config file using axios
    try {
        const res = await axios.post(config.endpoint_url, reqObj.body, { headers: reqObj.headers });
        console.log(`Request successful. Response status: ${res.status}`);
        cb();
    } catch (err) {
        console.error(`Error making request: ${err}`);
        cb(err);
    }
});

// Listen for incoming JSON strings from the server
socket.on("request", jsonStr => {
    // Add the incoming JSON string onto the fastq worker
    worker.push(jsonStr);
});
