services:
  client:
    build: ./client
    depends_on:
      - server
  server:
    build: ./server
    command: node app.js
    # ports:
    #   WEBHOOK_PORT:WEBHOOK_PORT
    #   INTERNAL_PORT:INTERNAL_PORT